// Auto-generated by scripts/update-substack.mjs
// Run `pnpm sync:blogs` to refresh the cache.
import type { SubstackArticle, SubstackDatasetMeta } from '$lib/types/blog';

export const substackArticles: SubstackArticle[] = [
  {
    "id": "173004050",
    "title": "My Scars Are My Blueprint",
    "slug": "my-scars-are-my-blueprint",
    "summary": "How past trauma gave me a reason to stop playing it safe and start building things that matter in New Zealand.",
    "url": "https://szuhan.substack.com/p/my-scars-are-my-blueprint",
    "publishedAt": "2025-09-07T09:52:03.521Z",
    "coverImage": "https://substackcdn.com/image/fetch/$s_!8qa6!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F08ae61a8-4eae-4421-94d0-c1009324846f_1400x977.webp",
    "tags": [],
    "readingTimeMinutes": null
  },
  {
    "id": "165444603",
    "title": "Beyond the Badges - Finding Meaning in the People Who Build Your Story",
    "slug": "beyond-the-badges-finding-meaning",
    "summary": "A Personal Quest for Connection and the Discovery of Life's Given Layers",
    "url": "https://szuhan.substack.com/p/beyond-the-badges-finding-meaning",
    "publishedAt": "2025-07-07T10:18:28.847Z",
    "coverImage": "https://substackcdn.com/image/fetch/$s_!MMTS!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fffa69ce0-230c-4540-a6e4-98a1df1251e3_5712x4284.heic",
    "tags": [],
    "readingTimeMinutes": null
  },
  {
    "id": "162806801",
    "title": "We could be a giant of another person's story ",
    "slug": "we-could-be-a-giant-of-another-persons",
    "summary": "",
    "url": "https://szuhan.substack.com/p/we-could-be-a-giant-of-another-persons",
    "publishedAt": "2025-05-25T02:08:53.918Z",
    "coverImage": "https://substackcdn.com/image/fetch/$s_!IQHs!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F4cfb73e6-1700-465a-a1a6-2d82aeb30f4c_1080x1080.jpeg",
    "tags": [],
    "readingTimeMinutes": null
  },
  {
    "id": "161452902",
    "title": "I Left My Family To Find Family",
    "slug": "i-left-my-family-to-find-family",
    "summary": "",
    "url": "https://szuhan.substack.com/p/i-left-my-family-to-find-family",
    "publishedAt": "2025-04-16T11:29:51.126Z",
    "coverImage": "https://substackcdn.com/image/fetch/$s_!yQco!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7e51f186-60c8-4072-ab92-feab16c62cbb_1179x851.jpeg",
    "tags": [],
    "readingTimeMinutes": null
  }
];

export const substackMeta: SubstackDatasetMeta = {
  "lastUpdated": "2025-09-17T23:38:59.651Z",
  "source": "https://szuhan.substack.com/api/v1/archive?sort=new&offset=0&limit=20"
};
